apiVersion: v1
kind: Service
metadata:
  name: gestionprojeet-service
  namespace: default
  labels:
    app: gestionprojeet
spec:
  type: ClusterIP
  selector:
    app: gestionprojeet
  ports:
  - name: http
    port: 8089
    targetPort: 8089
    protocol: TCP
