spring.datasource.url=jdbc:mysql://localhost:3306/projet202409?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
server.port=8089
application.security.jwt.secret-key=357638792F423F4428472B4B6250655368566D597133743677397A2443264629
spring.mail.username=nourlass50@gmail.com
spring.mail.password=qwua jsrz pfzo kvkq
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false